
services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    working_dir: /app
    command: sh -c "python seed.py && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  tester:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - ./report:/app/report
    working_dir: /app
    depends_on:
      - backend
    command: sh -c "pytest test/ --html=report/report.html"

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    working_dir: /app
    command: sh -c "npm install && npm run dev"
