services:
  services:
  backend:
    volumes:
      - ./backend:/app
    command: sh -c "python seed.py && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  frontend:
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    working_dir: /app
    command: sh -c "npm install && npm run dev"

